#!/usr/bin/bash

zls () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   		tar jtvf $1        ;;
            *.tar.gz)    		tar ztvf $1     ;;
	    *.tar)			tar tvf $1	;;		 
            *.rar | *.zip | *.7z)       7z l $1     ;;
            *)           		echo "'$1' is not supported " ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

zls $1

